resources:
- clusterrole.yaml
- serviceaccount.yaml
- clusterrolebinding.yaml
- deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: lehtux/aws-shield-controller
  newName: lehtux/aws-shield-controller
  newTag: v0.0.1
