apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-shield-controller
  namespace: kube-system
  annotations:
#    eks.amazonaws.com/role-arn:  arn:aws:iam::<account_number>:role/AWSShieldControllerServiceAccount
